sudo: required
dist: trusty
language: cpp
compiler: gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install jing
  - sudo apt-get -qq install libsdl2-dev
  - sudo apt-get -qq install libfreetype6-dev
  - sudo apt-get -qq install libasound2-dev
  - cmake --version
script: >
  python scripts/lint.py
  && mkdir build
  && cd build
  && cmake ..
  && make
  && ctest --verbose
