sudo: required
dist: trusty
language: cpp
compiler: gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libsdl2-dev jing
  - cmake --version
script: make lint && mkdir build && cd build && cmake .. && make && ctest -V
