image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform: x86
build:
  project: Procdraw.sln
test_script:
  - vstest.console /logger:Appveyor %CONFIGURATION%\ProcdrawTests.dll
