# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Procdraw

# Build settings
markdown: kramdown

exclude: [
  "bower.json",
  "browserslist",
  "gulpfile.js",
  "Makefile",
  "node_modules",
  "npm-debug.log",
  "bower_components",
  "package.json",
  "README.md"
]

collections:
  functions_generated:
    output: true
    permalink: /docs/functions/:path:output_ext

defaults:
  - scope:
      path: ""
      type: functions_generated
    values:
      layout: page
      section: docs
  - scope:
      path: "docs"
    values:
      section: docs
