name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      PROCDRAW_VISUAL_STUDIO_HOME: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
      PROCDRAW_VCVARS: vcvars32.bat
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Python dependencies
        shell: cmd
        run: >-
          python -m pip install --upgrade pip
          && python -m pip install -r requirements.txt
      - name: Lint
        shell: cmd
        run: >-
          call "%PROCDRAW_VISUAL_STUDIO_HOME%\\VC\\Auxiliary\\Build\\%PROCDRAW_VCVARS%"
          && MSBuild -t:Lint
      - name: Query vcpkg commit
        shell: cmd
        run: >-
          cd /D %VCPKG_INSTALLATION_ROOT%
          && git log -1 --pretty=format:"commit %%H%%nDate:  %%aD"
      - name: Install vcpkg dependencies
        run: vcpkg install catch2 glfw3 glm plog pugixml
      - name: Configure
        shell: cmd
        run: >-
          call "%PROCDRAW_VISUAL_STUDIO_HOME%\\VC\\Auxiliary\\Build\\%PROCDRAW_VCVARS%"
          && MSBuild -t:Configure -p:VcpkgRoot=%VCPKG_INSTALLATION_ROOT%
      - name: Compile
        shell: cmd
        run: >-
          call "%PROCDRAW_VISUAL_STUDIO_HOME%\\VC\\Auxiliary\\Build\\%PROCDRAW_VCVARS%"
          && MSBuild -t:Compile
      - name: Test
        shell: cmd
        run: >-
          call "%PROCDRAW_VISUAL_STUDIO_HOME%\\VC\\Auxiliary\\Build\\%PROCDRAW_VCVARS%"
          && MSBuild -t:Test
      - name: Build the website
        shell: cmd
        run: cd website && invoke build
