name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Python dependencies
        shell: cmd
        run: >-
          python -m pip install --upgrade pip
          && python -m pip install -r requirements.txt
      - name: Validate XML
        run: invoke validate-xml
      - name: Query vcpkg commit
        shell: cmd
        run: >-
          cd /D %VCPKG_INSTALLATION_ROOT%
          && git log -1 --pretty=format:"commit %%H%%nDate:  %%aD"
      - name: Install vcpkg dependencies
        run: vcpkg install catch2 plog pugixml wil
      - name: Build
        shell: cmd
        run: >-
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat"
          && mkdir build
          && cd build
          && cmake -G Ninja -D CMAKE_C_COMPILER=cl.exe -D CMAKE_CXX_COMPILER=cl.exe -D CMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake ..
          && cmake --build .
      - name: Test
        shell: cmd
        run: cd build && .\procdraw_tests.exe
      - name: Check source file headers
        run: invoke check-file-headers
      - name: Build the website
        run: invoke website.build
